# PD01 · Explorar y preparar AGROSAVIA

[Índice y distribución de las cuatro horas](../ejercicios/README.md) · [Guía de pandas](../docs/manual-pandas.md)

**Tiempo de trabajo: 60 minutos.** El objetivo es reconocer la estructura de un DataFrame y preparar medidas y fechas conservando los valores originales.

| Símbolo | Uso |
|:---:|---|
| 📘 | Concepto o función de apoyo. |
| ✅ | Evidencia que debe quedar visible. |
| ⚠️ | Límite de interpretación. |

Esta plantilla se encuentra en `ejercicios/PD01_exploracion_agrosavia.ipynb`. Antes de comenzar, se crea una copia en `soluciones/PD01_exploracion_agrosavia.ipynb` dentro del repositorio de cada estudiante. El desarrollo y la entrega se realizan en esa copia; la plantilla de `ejercicios/` se conserva como enunciado. En JupyterLab se puede duplicar el archivo y mover la copia a `soluciones/`, manteniendo el nombre indicado; si ya existe una solución, se continúa sobre ella. Las instrucciones se presentan en celdas Markdown; las celdas de código marcadas como **Desarrollo** contienen el espacio de trabajo. Cada actividad incluye una celda para explicar el resultado.

Se utiliza el kernel del entorno `.venv` del curso. Los CSV ya deben estar descargados mediante `kit/00_datos.py`. La celda inicial prepara las rutas y carga únicamente las entradas de este ejercicio; el desarrollo del análisis corresponde al estudiante. Este notebook se ejecuta de forma independiente.

**Apoyo en el manual:** secciones 1–5 y la receta de registros en revisión de la sección 11.

## Ubicación de trabajo: ruta visible

La carpeta base es `/mnt/c/Users/TUPTC/bigdata` y el repositorio está dentro de `big-data-postgraduate`. Desde Ubuntu:

```bash
cd /mnt/c/Users/TUPTC/bigdata
cd big-data-postgraduate
source .venv/bin/activate
jupyter lab
```

La siguiente celda declara `REPO` como una cadena de texto que puedes cambiar. `RAW` contiene la carpeta de los CSV y `OUT` la carpeta de tus resultados. No se busca el repositorio automáticamente ni se modifica el directorio del kernel. Si aparece `FileNotFoundError`, revisa la ruta impresa y el nombre del archivo. Las rutas absolutas funcionan aunque el notebook esté en `ejercicios/` o `soluciones/`.

## Preparación

Lee primero las rutas y ajusta `REPO` a tu copia. Después ejecuta cada lectura por separado: `sep` define el separador, `dtype=str` preserva códigos y `keep_default_na=False` conserva vacíos y marcadores. Observa el DataFrame antes de desarrollar las actividades. Cada llamada a `read_csv` muestra sus opciones completas.

In [1]:
import pandas as pd
import os

REPO = "/mnt/c/Users/TUPTC/bigdata/big-data-postgraduate"
RAW = REPO + "/kit/data/raw"
OUT = REPO + "/kit/salidas/soluciones/PD01"
print("Datos:", RAW)
print("Salidas:", OUT)
print("pandas:", pd.__version__)
# Crear solamente la carpeta destinada a tus resultados.
os.makedirs(OUT, exist_ok=True)

Datos: /mnt/c/Users/TUPTC/bigdata/big-data-postgraduate/kit/data/raw
Salidas: /mnt/c/Users/TUPTC/bigdata/big-data-postgraduate/kit/salidas/soluciones/PD01
pandas: 2.2.3

In [2]:
suelo = pd.read_csv(
    RAW + "/agrosavia.csv",
    sep=",",
    encoding="utf-8-sig",
    dtype=str,
    keep_default_na=False
)
display(suelo.head())
print(suelo.shape)

,Secuencial,Fecha de Análisis,Departamento,Municipio,Cultivo,Estado,Tiempo de establecimiento,Topografia,Drenaje,Riego,...,Conductividad electrica,Hierro disponible olsen,Cobre disponible,Manganeso disponible Olsen,Zinc disponible Olsen,Boro disponible,Hierro disponible doble acido,Cobre disponible doble acido,Manganeso disponible doble acido,Zinc disponible doble acido
0,1,7/01/2014,NARIÑO,SAN ANDRÉS DE TUMACO,No Indica,No indica,No indica,No indica,No indica,No indica,...,0.133,66.39,1.700,1.700,1.5,0.187,ND,ND,ND,ND
1,2,21/08/2014,HUILA,SANTA MARÍA,Granadilla,Establecido,De 1 a 5 años,Pendiente,Buen drenaje,No Tiene,...,2.749,250.9,3.7,29.4,28.70,2.084,ND,ND,ND,ND
2,3,22/08/2014,ANTIOQUIA,LIBORINA,Café,Por establecer,No indica,Pendiente,Mal drenaje,No Tiene,...,0.328,390,11.10,8.299,5,0.085,ND,ND,ND,ND
3,4,22/08/2014,ANTIOQUIA,LIBORINA,Maracuyá,Por establecer,No indica,Ondulado,Mal drenaje,No Tiene,...,0.171,200,4.2,4.699,1,0.229,ND,ND,ND,ND
4,5,22/08/2014,ANTIOQUIA,LIBORINA,Café,Por establecer,No indica,Ondulado,Mal drenaje,No Tiene,...,0.323,117.9,3.8,4.600,0.700,0.139,ND,ND,ND,ND

(92738, 32)

## 1. Inspección inicial · 10 minutos

Presentar la cantidad de filas y columnas, los nombres de las columnas, sus tipos y cinco registros. Explicar qué representa una fila y por qué la lectura inicial conserva los campos como texto.

📘 **Apoyo:** `shape`, `columns`, `dtypes`, `head` e `info`.

✅ **Comprobación:** El corte del manifiesto contiene 92.738 filas y 32 columnas. La tabla original debe conservar esa cantidad de filas durante el ejercicio.

In [3]:
# Desarrollo de la actividad 1
# Mostrar dimensiones, tipos y primeros registros de suelo.
print("Dimensiones de la tabla (filas, columnas):", suelo.shape)
print("\nNombres de las columnas:")
print(list(suelo.columns))
print("\nTipos de datos (dtypes):")
print(suelo.dtypes)
print("\nInformación general (info):")
suelo.info()
print("\nPrimeros 5 registros (head):")
display(suelo.head())
# Guardar el total de filas original para los controles posteriores.
total_filas_original = suelo.shape[0]
print(f"\n[Comprobación] Total de filas original guardado: {total_filas_original}")

Dimensiones de la tabla (filas, columnas): (92738, 32)

Nombres de las columnas:
['Secuencial', 'Fecha de Análisis', 'Departamento', 'Municipio', 'Cultivo', 'Estado', 'Tiempo de establecimiento', 'Topografia', 'Drenaje', 'Riego', 'Fertilizantes aplicados', 'pH agua:suelo', 'Materia organica', 'Fósforo Bray II', 'Azufre Fosfato monocalcico', 'Acidez Intercambiable', 'Aluminio intercambiable', 'Calcio intercambiable', 'Magnesio intercambiable', 'Potasio intercambiable', 'Sodio intercambiable', 'capacidad de intercambio cationico', 'Conductividad electrica', 'Hierro disponible olsen', 'Cobre disponible', 'Manganeso disponible Olsen', 'Zinc disponible Olsen', 'Boro disponible', 'Hierro disponible doble acido', 'Cobre disponible doble acido', 'Manganeso disponible doble acido', 'Zinc disponible doble \xa0acido']

Tipos de datos (dtypes):
Secuencial                            object
Fecha de Análisis                     object
Departamento                          object
Municipio                             object
Cultivo                               object
Estado                                object
Tiempo de establecimiento             object
Topografia                            object
Drenaje                               object
Riego                                 object
Fertilizantes aplicados               object
pH agua:suelo                         object
Materia organica                      object
Fósforo Bray II                       object
Azufre Fosfato monocalcico            object
Acidez Intercambiable                 object
Aluminio intercambiable               object
Calcio intercambiable                 object
Magnesio intercambiable               object
Potasio intercambiable                object
Sodio intercambiable                  object
capacidad de intercambio cationico    object
Conductividad electrica               object
Hierro disponible olsen               object
Cobre disponible                      object
Manganeso disponible Olsen            object
Zinc disponible Olsen                 object
Boro disponible                       object
Hierro disponible doble acido         object
Cobre disponible doble acido          object
Manganeso disponible doble acido      object
Zinc disponible doble  acido          object
dtype: object

Información general (info):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92738 entries, 0 to 92737
Data columns (total 32 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Secuencial                          92738 non-null  object
 1   Fecha de Análisis                   92738 non-null  object
 2   Departamento                        92738 non-null  object
 3   Municipio                           92738 non-null  object
 4   Cultivo                             92738 non-null  object
 5   Estado                              92738 non-null  object
 6   Tiempo de establecimiento           92738 non-null  object
 7   Topografia                          92738 non-null  object
 8   Drenaje                             92738 non-null  object
 9   Riego                               92738 non-null  object
 10  Fertilizantes aplicados             92738 non-null  object
 11  pH agua:suelo                       92738 non-null  object
 12  Materia organica                    92738 non-null  object
 13  Fósforo Bray II                     92738 non-null  object
 14  Azufre Fosfato monocalcico          92738 non-null  object
 15  Acidez Intercambiable               92738 non-null  object
 16  Aluminio intercambiable             92738 non-null  object
 17  Calcio intercambiable               92738 non-null  object
 18  Magnesio intercambiable             92738 non-null  object
 19  Potasio intercambiable              92738 non-null  object
 20  Sodio intercambiable                92738 non-null  object
 21  capacidad de intercambio cationico  92738 non-null  object
 22  Conductividad electrica             92738 non-null  object
 23  Hierro disponible olsen             92738 non-null  object
 24  Cobre disponible                    92738 non-null  object
 25  Manganeso disponible Olsen          92738 non-null  object
 26  Zinc disponible Olsen               92738 non-null  object
 27  Boro disponible                     92738 non-null  object
 28  Hierro disponible doble acido       92738 non-null  object
 29  Cobre disponible doble acido        92738 non-null  object
 30  Manganeso disponible doble acido    92738 non-null  object
 31  Zinc disponible doble  acido        92738 non-null  object
dtypes: object(32)
memory usage: 22.6+ MB

Primeros 5 registros (head):

,Secuencial,Fecha de Análisis,Departamento,Municipio,Cultivo,Estado,Tiempo de establecimiento,Topografia,Drenaje,Riego,...,Conductividad electrica,Hierro disponible olsen,Cobre disponible,Manganeso disponible Olsen,Zinc disponible Olsen,Boro disponible,Hierro disponible doble acido,Cobre disponible doble acido,Manganeso disponible doble acido,Zinc disponible doble acido
0,1,7/01/2014,NARIÑO,SAN ANDRÉS DE TUMACO,No Indica,No indica,No indica,No indica,No indica,No indica,...,0.133,66.39,1.700,1.700,1.5,0.187,ND,ND,ND,ND
1,2,21/08/2014,HUILA,SANTA MARÍA,Granadilla,Establecido,De 1 a 5 años,Pendiente,Buen drenaje,No Tiene,...,2.749,250.9,3.7,29.4,28.70,2.084,ND,ND,ND,ND
2,3,22/08/2014,ANTIOQUIA,LIBORINA,Café,Por establecer,No indica,Pendiente,Mal drenaje,No Tiene,...,0.328,390,11.10,8.299,5,0.085,ND,ND,ND,ND
3,4,22/08/2014,ANTIOQUIA,LIBORINA,Maracuyá,Por establecer,No indica,Ondulado,Mal drenaje,No Tiene,...,0.171,200,4.2,4.699,1,0.229,ND,ND,ND,ND
4,5,22/08/2014,ANTIOQUIA,LIBORINA,Café,Por establecer,No indica,Ondulado,Mal drenaje,No Tiene,...,0.323,117.9,3.8,4.600,0.700,0.139,ND,ND,ND,ND

[Comprobación] Total de filas original guardado: 92738

**Interpretación del resultado:**

La tabla cuenta con 92738 filas y 32 columnas, cada fila representa un registro de datos, se evidencia que conserva una lectura de datos inicial ya que se usa el formato pd.read sin especificar el tipo de datos. Tambien es de notar que pandas lee las columnas como tipo texto y realiza una lectura generica para evitar generar errores.

## 2. Diagnóstico de cinco campos · 10 minutos

Construir una tabla llamada `perfil` para `Secuencial`, `Fecha de Análisis`, `Departamento`, `Municipio` y `pH agua:suelo`. Para cada campo se registran los nulos de pandas, los textos vacíos después de retirar espacios y los marcadores `ND`. Las tres situaciones se cuentan por separado.

📘 **Apoyo:** `isna`, `.str.strip`, `.str.upper`, `.eq` y `sum`.

✅ **Comprobación:** `perfil` debe tener una fila por campo. Con `keep_default_na=False`, un texto vacío o `ND` no se convierte automáticamente en un nulo.

In [7]:
# Desarrollo de la actividad 2
# Crear y mostrar perfil con las cinco columnas solicitadas.
import pandas as pd
campos = ['Secuencial', 'Fecha de Análisis', 'Departamento', 'Municipio', 'pH agua:suelo']
filas_perfil = []
for col in campos:
    nulos_pandas = suelo[col].isna().sum()
    textos_vacios = (suelo[col].astype(str).str.strip() == '').sum()
    marcadores_nd = (suelo[col].astype(str).str.strip().str.upper() == 'ND').sum() 
    filas_perfil.append({
        'Campo': col,
        'Nulos_Pandas': nulos_pandas,
        'Textos_Vacios': textos_vacios,
        'ND': marcadores_nd
    })
perfil = pd.DataFrame(filas_perfil)
display(perfil)

               Campo  Nulos_Pandas  Textos_Vacios  ND
0         Secuencial             0              0   0
1  Fecha de Análisis             0              0   0
2       Departamento             0              0   0
3          Municipio             0              2   0
4      pH agua:suelo             0              0   0

**Interpretación del resultado:**

La tabla contirnr una fila por cada uno de los 5 campos analizados lo cual permite verificar de forma independiente cada anomalia, debido a que se conservan los tipos de texto originales se detecta con precision los espacios vacios y los textos ND lo cual no habria sido posible al convertir el texto.

## 3. Conversión de pH y fecha · 15 minutos

Crear `ph` desde `pH agua:suelo` y `fecha_dt` desde `Fecha de Análisis`. Utilizar conversión numérica con `errors="coerce"` y fecha con formato `%d/%m/%Y`. Conservar los originales. Distinguir entradas vacías de textos no vacíos que no pudieron convertirse.

📘 **Apoyo:** `pd.to_numeric`, `.str.replace`, `pd.to_datetime`, `isna` y máscaras booleanas.

✅ **Comprobación:** Se muestran los conteos de conversiones fallidas y hasta cinco ejemplos con su valor original. No se reemplazan medidas ausentes por cero.

In [8]:
# Desarrollo de la actividad 3
# Crear suelo["ph"] y suelo["fecha_dt"].
ph_limpio = suelo['pH agua:suelo'].astype(str).str.replace(',', '.', regex=False)
suelo['ph'] = pd.to_numeric(ph_limpio, errors='coerce')
suelo['fecha_dt'] = pd.to_datetime(suelo['Fecha de Análisis'], format='%d/%m/%Y', errors='coerce')

# Mostrar los fallos de conversión y sus valores originales.
es_nulo_orig_ph = suelo['pH agua:suelo'].isna() | (suelo['pH agua:suelo'].astype(str).str.strip() == '')
fallo_ph = suelo['ph'].isna() & ~es_nulo_orig_ph
print(f"Total de conversiones fallidas en 'ph': {fallo_ph.sum()}")
print("Hasta 5 ejemplos originales con fallo en 'ph':")
display(suelo.loc[fallo_ph, ['pH agua:suelo', 'ph']].head(5))
es_nulo_orig_fecha = suelo['Fecha de Análisis'].isna() | (suelo['Fecha de Análisis'].astype(str).str.strip() == '')
fallo_fecha = suelo['fecha_dt'].isna() & ~es_nulo_orig_fecha
print(f"\nTotal de conversiones fallidas en 'fecha_dt': {fallo_fecha.sum()}")
print("Hasta 5 ejemplos originales con fallo en 'fecha_dt':")
display(suelo.loc[fallo_fecha, ['Fecha de Análisis', 'fecha_dt']].head(5))

Total de conversiones fallidas en 'ph': 11
Hasta 5 ejemplos originales con fallo en 'ph':

      pH agua:suelo  ph
7282          4..01 NaN
46528        >10.00 NaN
46530        >10.00 NaN
52903         <3.80 NaN
56330         <3.80 NaN

Total de conversiones fallidas en 'fecha_dt': 0
Hasta 5 ejemplos originales con fallo en 'fecha_dt':

Empty DataFrame
Columns: [Fecha de Análisis, fecha_dt]
Index: []

**Interpretación del resultado:**

Se realiza la conversion de los valores incompatibles en nulos para no interrumpir la ejecucion, tambien se usan mascaras booleanas para separar los campos que venian vacios o nulos, se mantienen los datos originales y se reemplazan los campos ausentes pos ceros manteniendo la cantidad de datos faltantes.

## 4. Registros para revisión · 15 minutos

Crear la columna booleana `en_revision`. Se marca una fila si su pH es ausente, está fuera de `[0, 14]` o su fecha no se pudo interpretar. Contar por separado cada motivo y el total de filas marcadas. Conservar todas las observaciones.

📘 **Apoyo:** `between`, `isna`, `|`, `~`, `.loc` y `value_counts`.

✅ **Comprobación:** Las filas marcadas y no marcadas deben sumar el total original. Una misma fila puede tener varios motivos; por eso la suma de los motivos no necesariamente coincide con el total marcado.

In [9]:
# Desarrollo de la actividad 4
# Crear en_revision y los conteos por motivo.
ph_ausente = suelo['ph'].isna()
ph_fuera_rango = ~suelo['ph'].between(0, 14) & ~ph_ausente 
fecha_fallida = suelo['fecha_dt'].isna() & ~(suelo['Fecha de Análisis'].isna() | (suelo['Fecha de Análisis'].astype(str).str.strip() == ''))
conteo_ph_ausente = ph_ausente.sum()
conteo_ph_fuera_rango = ph_fuera_rango.sum()
conteo_fecha_fallida = fecha_fallida.sum()
print("Conteo por motivo:")
print(f"- pH ausente: {conteo_ph_ausente}")
print(f"- pH fuera de rango [0, 14]: {conteo_ph_fuera_rango}")
print(f"- Fecha no interpretable: {conteo_fecha_fallida}")
suelo['en_revision'] = ph_ausente | ph_fuera_rango | fecha_fallida
total_marcadas = suelo['en_revision'].sum()
total_no_marcadas = (~suelo['en_revision']).sum()
print(f"\nTotal de filas marcadas para revisión: {total_marcadas}")
print(f"Total de filas no marcadas: {total_no_marcadas}")
# Comprobar la conservación del total original con assert.
assert (total_marcadas + total_no_marcadas) == total_filas_original, "¡Error! Las filas marcadas y no marcadas no suman el total original."
print("\n[Comprobación Exitosa] Las filas marcadas y no marcadas suman exactamente el total original de filas.")

Conteo por motivo:
- pH ausente: 11
- pH fuera de rango [0, 14]: 0
- Fecha no interpretable: 0

Total de filas marcadas para revisión: 11
Total de filas no marcadas: 92727

[Comprobación Exitosa] Las filas marcadas y no marcadas suman exactamente el total original de filas.

**Interpretación del resultado:**

se crea una variable booleana para identificar las filas que representan anomalias críticas en las mediciones. se realiza el conteo de las incidencias por separado dado a que las filas puedan incurrir con fallos simultaneos, esto en base a conservar la integridad de las observaciones originales y garantizar que no se eliminen las filas.

## 5. Evidencias y conclusiones · 10 minutos

Construir `controles` con las columnas `control` y `cantidad`: total de entrada, pH sin número, pH fuera del intervalo, fecha no interpretable y total de filas en revisión. Exportar a `OUT + "/controles_agrosavia.csv"` sin índice. Redactar dos hallazgos apoyados en los conteos.

📘 **Apoyo:** `pd.DataFrame`, `to_csv(index=False)` y las tablas de las actividades anteriores.

✅ **Comprobación:** El archivo se genera dentro de la ruta `OUT`. Cada hallazgo menciona un conteo y explica su significado o limitación.

In [10]:
# Desarrollo de la actividad 5
# Construir controles, mostrarlo y exportarlo a OUT.
import os
datos_controles = [
    {"control": "Total de entrada", "cantidad": total_filas_original},
    {"control": "pH sin número", "cantidad": fallo_ph.sum()},
    {"control": "pH fuera del intervalo", "cantidad": conteo_ph_fuera_rango},
    {"control": "Fecha no interpretable", "cantidad": conteo_fecha_fallida},
    {"control": "Total de filas en revisión", "cantidad": total_marcadas}
]
controles = pd.DataFrame(datos_controles)
print("Tabla de controles generada:")
display(controles)
os.makedirs(OUT, exist_ok=True)
ruta_salida = os.path.join(OUT, "controles_agrosavia.csv")
controles.to_csv(ruta_salida, index=False)
print(f"\n[Comprobación Exitosa] Archivo exportado correctamente en: {ruta_salida}")

Tabla de controles generada:

                      control  cantidad
0            Total de entrada     92738
1               pH sin número        11
2      pH fuera del intervalo         0
3      Fecha no interpretable         0
4  Total de filas en revisión        11

[Comprobación Exitosa] Archivo exportado correctamente en: /mnt/c/Users/TUPTC/bigdata/big-data-postgraduate/kit/salidas/soluciones/PD01/controles_agrosavia.csv

**Interpretación del resultado:**

se consolida la tabla controles el cual recopila las metricas globales del proceso de auditoria, realiza la exportacion, realiza el conteo de los registros, se evidencia la presencia de errores tipograficos o mediciones imposibles en campo.

## Entrega

El notebook completado se conserva como `soluciones/PD01_exploracion_agrosavia.ipynb`. La salida regenerable es `kit/salidas/soluciones/PD01/controles_agrosavia.csv`.

✅ Deben quedar visibles el perfil, los controles de conversión, la conciliación de filas y dos hallazgos. El notebook debe ejecutar todas las celdas en orden después de reiniciar el kernel.

⚠️ El intervalo de pH es un control de dominio para esta práctica. No determina por sí solo una recomendación agronómica. La frecuencia de análisis de suelo no representa automáticamente la distribución de los suelos de todo el territorio.